### ISSUE TITLE
Error during installation process

### ISSUE THREAD

**Issue by lyqRicky** [raphaelvdumas/OASES#2]
May I ask what the following errors are during the installation process？

![Image](https://github.com/user-attachments/assets/4707c816-7090-4610-930e-7f0ecfd9e51f)

**Comment by raphaelvdumas** [comment]
This comes from GNU. I’ve just released an updated version: @tag/v3.1.0. Please download it and let me know if it fixes the problem

**Comment by raphaelvdumas** [comment]
This comes from GNU. I’ve just released an updated version: @tag/v3.1.0. Please download it and let me know if it fixes the problem

**Comment by lyqRicky** [comment]
Thank you for your reply, but I still encounter the following error message after downloading the new version

**Comment by lyqRicky** [comment]
Thank you for your reply, but I still encounter the following error message after downloading the new version

![Image](https://github.com/user-attachments/assets/d56c3c87-9fc4-462d-8d48-29fa3dc76667)

**Comment by raphaelvdumas** [comment]
I've updated the release version. Let me know if you need anything. In the meantime, I'll be working on a portable edition of OASES.

**Comment by lyqRicky** [comment]
The following errors occurred during the installation process

![Image](https://github.com/user-attachments/assets/e44da0ff-71b9-4753-bf5f-af0479cae83f)

**Comment by raphaelvdumas** [comment]
If you're on Windows, I have (pre)released portable versions for both 32-bit and 64-bit (compute only, no plotting).

For Ubuntu, I'm currently facing issues with the plotting functions due to Plotmtv no longer being available. It seems likely that, at some point, this will become a compute-only library.

**Comment by lyqRicky** [comment]
I am using a Windows system and I want to use oases to calculate the reflection coefficients of rough ice and water layers。

**Comment by lyqRicky** [comment]
I am using a Windows system and I want to use oases to calculate the reflection coefficients of rough ice and water layers.

**Comment by raphaelvdumas** [comment]
Oh, then you can download the Windows 32 or Windows 64 from the release page, you will be able to use oasr directly in a cmd.exe on Windows.

**Comment by lyqRicky** [comment]
I downloaded and calculated successfully, thank you very much!

**Comment by raphaelvdumas** [comment]
Perfect! Let me know if you encounter any issues
